services:
  application:
    ports:
      - "8080:8080"
    container_name: docker-project
    image: kimkyungho/docker-project
    restart: always
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root1234!!
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --bind-address=0.0.0.0