services:
  mysql:
    image: mysql:8.0
    container_name: docker-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: RESERVATION
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root1234!!
      TZ: 'Asia/Seoul'
    volumes:
      - /home/ubuntu/mysql/data:/var/lib/mysql
      - /mysql/conf.d:/etc/mysql/conf.d
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
      - "--bind-address=0.0.0.0"
    networks:
      - docker_network

  application:
    ports:
      - "8080:8080"
    container_name: docker-project
    image: kimkyungho/docker-project
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/RESERVATION
      SPRING_DATASOURCE_USERNAME: "kimkyungho"
      SPRING_DATASOURCE_PASSWORD: "kimkyugnho1234!!"
    networks:
      - docker_network

networks:
  docker_network: